[FIX] 3D panel camera sync functionality
Lichtblick-Suite/lichtblick pull request #263
Opened 2024-11-15 12:45 UTC by ctw-joao-luis

**User-Facing Changes**
The option to sync panels on 3D panel is now operational again. The user can have 2 or more panels synced up and, for instance, by moving the camera on one panel, the other panel will simulate the same behavior while the Camera sync option is activated.

**Description**
After a while of studying the code I realized that problem wasn't on 3D panel itself, all the logic was correct there, but I observe that, no matter what, the sharedPanelState property would stay undefined even with the setter receiving all the correct data. 

**Checklist**

- [ ] The web version was tested and it is running ok
- [ ] The desktop version was tested and it is running ok
- [ ] This change is covered by unit tests
- [ ] Files constants.ts, types.ts and *.style.ts have been checked and relevant code snippets have been relocated

2024-11-18 15:52 UTC, laisspportugal commented
Congrats on the PR description, very informative <3

2024-11-20 09:58 UTC, aneuwald-ctw requested changes

2024-11-20 09:59 UTC, aneuwald-ctw commented on packages/suite-base/src/providers/CurrentLayoutProvider/hooks/useUpdateSharedPanelState.test.ts
> +  let setLayoutState: jest.Mock;
Avoid to use let as much as possible

2024-11-20 10:02 UTC, luluiz submitted a review, later dismissed

2024-11-20 11:56 UTC, ctw-joao-luis commented on packages/suite-base/src/providers/CurrentLayoutProvider/hooks/useUpdateSharedPanelState.test.ts
> +  let setLayoutState: jest.Mock;
Change implemented 👍

2024-11-20 14:12 UTC, aneuwald-ctw approved these changes
Thanks for the changes. Good job!

2024-11-20 14:13 UTC, merged