feat: add pie chart plugin
lichtblick-suite/lichtblick pull request #315
Opened 2024-12-24 16:38 UTC by yukkysaito

**User-Facing Changes**

Thank you for maintaining Lichtblick.

I have created a plugin to display a float32 array as a pie chart. I developed it based on the Gauge plugin and used Recharts as the foundation. However, I’m not yet familiar with Lichtblick's coding practices, so the current implementation is just at a functional level. Could you kindly provide support on what would be needed to make it suitable for merging?

Additionally, the Gauge plugin I referenced has recently undergone significant refactoring in [this PR](https://github.com/Lichtblick-Suite/lichtblick/pull/286). The Pie Chart plugin was developed based on the pre-refactored version.
**Description**
![image](https://github.com/user-attachments/assets/892e12e3-03b9-4f8e-a786-9eecebe28015)

[Screencast from 2024年12月10日 22時49分54秒.webm](https://github.com/user-attachments/assets/a631f5bc-d09d-47e2-a4de-bfc3e46d7ab8)

**Checklist**

- [ ] The web version was tested and it is running ok
- [ ] The desktop version was tested and it is running ok
- [ ] This change is covered by unit tests
- [ ] Files constants.ts, types.ts and *.style.ts have been checked and relevant code snippets have been relocated

2024-12-26 13:33 UTC, luluiz commented
Hi @yukkysaito,
**Thank you** in advance for your contribution. 
As a team, we'll discuss this contribution to follow up on your PR.
Regarding Lichtblick's coding practices, we recently started improving the practices applied to the project, and these improvements are currently in progress based on some approved ADRs.

The team will get back to you soon.

2025-01-08 10:26 UTC, laisspportugal commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +// SPDX-License-Identifier: Apache-2.0
Can you please verify the license? Since we use MPL-2.0 why do you think is necessary to change to Apache?

2025-01-08 10:32 UTC, laisspportugal commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +// SPDX-License-Identifier: Apache-2.0
This comment applies to all files

2025-01-08 10:48 UTC, laisspportugal commented
Hello @yukkysaito 

We discussed as a team and we will evaluate your PR and leave some comments for you.
We already enabled the pipeline checks. Can you please them?
One tip for you is to run yarn install and them commit the changes on the yarn lock file.

Best Regards,
Lichtblick team

2025-01-14 01:50 UTC, yukkysaito commented
@luluiz @laisspportugal Thank you for your comment. I was on a business trip overseas until recently, so my reply was delayed.
I will address each matter in order, so please wait a little longer.

2025-03-26 01:58 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +// SPDX-License-Identifier: Apache-2.0
Sure. I'll change it

2025-03-29 22:40 UTC, yukkysaito commented on packages/suite-base/src/components/SettingsTreeEditor/NodeEditor.tsx
> +
@Tucker925H This code is caused conflicts.
Could you please check?
```
yukky@yukky:~/workspace/lichtblick$ yarn run web:build:prod
webpack 5.98.0 compiled successfully in 52 ms

main:
  assets by status 32.4 MiB [cached] 119 assets
  orphan modules 20.7 MiB [orphan] 5462 modules
  runtime modules 74.8 KiB 151 modules
  built modules 49.1 MiB (javascript) 3.15 MiB (asset) [built]
    modules by path ../../node_modules/ 43 MiB (javascript) 2.82 MiB (asset)
      javascript modules 41.6 MiB 2322 modules
      asset modules 486 KiB (javascript) 2.82 MiB (asset) 62 modules
      json modules 887 KiB 16 modules
    modules by path ../../packages/ 6.07 MiB (javascript) 340 KiB (asset) 194 modules
    modules by path ./ 44.6 KiB
      ./entrypoint.tsx + 23 modules 44.6 KiB [built] [code generated]
      ./terminal-highlight (ignored) 15 bytes [built] [code generated]
    modules by mime type image/svg+xml 3.17 KiB
      data:image/svg+xml;base64,PHN2ZyB3aWR0aD0i.. 1.59 KiB [built] [code generated]
      data:image/svg+xml;base64,PHN2ZyB3aWR0aD0i.. 1.59 KiB [built] [code generated]
    + 26 modules

  ERROR in ./packages/suite-base/src/components/SettingsTreeEditor/NodeEditor.tsx:32:3
  TS2440: Import declaration conflicts with local declaration of 'NodeEditorProps'.
      30 | import { useStyles } from "@lichtblick/suite-base/components/SettingsTreeEditor/NodeEditor.style";
      31 | import {
    > 32 |   NodeEditorProps,
         |   ^^^^^^^^^^^^^^^
      33 |   SelectVisibilityFilterValue,
      34 | } from "@lichtblick/suite-base/components/SettingsTreeEditor/types";
      35 | import Stack from "@lichtblick/suite-base/components/Stack";
```

2025-04-01 08:21 UTC, Tucker925H commented on packages/suite-base/src/components/SettingsTreeEditor/NodeEditor.tsx
> +
fixed at https://github.com/lichtblick-suite/lichtblick/pull/315/commits/3ac0731d9c05a255a0e189954039e2ccc4ad3dc7

2025-04-01 08:27 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/useChartData.ts
> +        name, // ← ここは絶対に string 型
```suggestion
        name,
```

2025-04-01 08:28 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/types.ts
> +// SPDX-FileCopyrightText: Copyright (C) 2023-2024 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)<lichtblick@bmwgroup.com>
```suggestion
```

2025-04-01 08:33 UTC, yukkysaito commented
@luluiz @laisspportugal Thank you for always helping me. 
Could you please review this PR?

2025-04-02 01:53 UTC, Tucker925H commented
@luluiz @laisspportugal (CC: @yukkysaito  ) 

Hi team,

I've implemented the PieChart feature based on @yukkysaito  original code and made necessary refactors to improve maintainability and clarity.

While verifying the behavior, I encountered an issue in the development desktop environment where the app launches but displays a blank (white) screen. I’m attaching a video for reference.

🔧 Development environment steps that led to the issue:
```bash
# Start Webpack dev server
yarn desktop:start

# Launch Electron app (after the server is ready)
yarn desktop:start
```
➡️ Result: Desktop app opens but remains on a white screen.

```bash
LIBGL_ALWAYS_SOFTWARE=1 yarn desktop:start
```
➡️ A white screen appeared as well.

[Screencast from 2025年04月02日 10時36分16秒.webm](https://github.com/user-attachments/assets/fc7653f6-8a8f-424a-9226-24cb2b79ef56)

```error
Unable to load preload script: /home/takayukihonda/document/upstream/lichtblick/desktop/.webpack/main/preload.js
(anonymous) @ VM111 renderer_init:2
VM111 renderer_init:2 SecurityError: Failed to read the 'cookie' property from 'Document': Access is denied for this document.
    at eval (index.ts:36:34)
    at ../../packages/suite-desktop/src/preload/index.ts (VM113 preload.js:1181:1)
    at __webpack_require__ (VM113 preload.js:1373:32)
    at fn (VM113 preload.js:1510:21)
    at eval (index.ts:2:95)
    at ./index.ts (VM113 preload.js:1203:1)
    at __webpack_require__ (VM113 preload.js:1373:32)
    at VM113 preload.js:2325:37
    at Object.<anonymous> (VM113 preload.js:2327:12)
    at Object.<anonymous> (VM113 preload.js:2329:3)
(anonymous) @ VM111 renderer_init:2
```

✅ However, the production version works fine with the following:
```bash
# Build for production
yarn run desktop:build:prod

# Package for Linux
yarn run package:linux

# Install the generated .deb file
sudo dpkg -i dist/lichtblick-1.11.0-linux-amd64.deb

# Launch the installed app
lichtblick
```
➡️ Result: The packaged Linux build runs successfully without issues.

[Screencast from 2025年04月02日 10時42分30秒.webm](https://github.com/user-attachments/assets/743a44fa-b1fe-463e-a4af-3a6a8cbe541a)

Is there anything that might be causing the white screen in the dev environment?

For reference, the web version works correctly in both development and production environments.

🖥️ My development environment:
Hardware: Lenovo ThinkPad X1 Extreme Gen 5
Memory: 32.0GB
CPU: Intel Core i7-12700H (12th Gen, 20 threads)
Graphics: NVIDIA GeForce RTX 3060 Mobile / Intel ADL GT2
Disk: 512.1GB SSD
OS: Ubuntu 22.04.5 LTS

Let me know if any further details are needed!

Thanks 🙇

2025-04-08 07:51 UTC, yukkysaito commented
@luluiz @laisspportugal friendly ping :pray:

2025-05-01 07:37 UTC, go-sakayori commented
@luluiz @laisspportugal 
I’m pinging to check on the status of this PR. The changes look very useful, and I’d love to see it merged.
One quick question: just like the other PR https://github.com/lichtblick-suite/lichtblick/pull/340, do we need to push a dummy commit to trigger the pipeline?

2025-05-14 19:16 UTC, aneuwald-ctw commented
> @luluiz @laisspportugal I’m pinging to check on the status of this PR. The changes look very useful, and I’d love to see it merged. One quick question: just like the other PR #340, do we need to push a dummy commit to trigger the pipeline?

Hey @go-sakayori, so sorry for the late answer. So, yes, I would kindly ask you to make a dummy commit, you can amend a new message or whatever, just to run the pipelines. 

As soon as it has ran, let's see the lint / test problems. In the mean while, I will be reviewing your PR to check if everything is ok!

Thanks again for the understanding and let's merge this!

Cheers,
Alex

2025-05-16 10:16 UTC, aneuwald-ctw commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +              {data.map((entry, index) => (
don't use index as key for arrays.

2025-05-16 10:18 UTC, aneuwald-ctw commented on packages/suite-base/src/panels/PieChart/settings.ts
> +const supportedDataTypes = [
extract to a file "constants.ts"

2025-05-16 10:29 UTC, aneuwald-ctw commented on packages/suite-base/src/components/SettingsTreeEditor/NodeEditor.tsx
> +      {props.panelTitle === "Pie Chart" && (
I don't think it is a good ideia to create an "if" here and rendering settings based on panel title, even because the title can (and will) change in the future. 

Please, check out other panels and use the same logic to render custom settings on SettingsTreeEditor.

Gauge is a really great example as It is very simple to understand:

```ts
const settingsTree = useSettingsTree({
    config,
    pathParseError: state.pathParseError,
    error: state.error?.message,
  });
  useEffect(() => {
    context.updatePanelSettingsEditor({
      actionHandler: settingsActionHandler,
      nodes: settingsTree,
    });
  }, [context, settingsActionHandler, settingsTree]);
```

also check: packages/suite-base/src/panels/Gauge/useSettingsTree.ts

2025-05-16 10:29 UTC, aneuwald-ctw commented on packages/suite-base/src/components/SettingsTreeEditor/index.tsx
> +          <NodeEditor {...nodeProps} panelTitle={panelInfo?.title} key={nodeProps.key} />
don't need it here.

2025-05-16 10:31 UTC, aneuwald-ctw commented on packages/suite-base/src/panels/PieChart/types.ts
> +export type State = {
Please as it is exported, don't use so generic names, it can be confusing when exporting and leading to errors. Use specific names, like: PieChartConfig, PieCharState, PieChartAction, PieChartDatum

2025-05-16 16:57 UTC, luluiz requested changes

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/components/SettingsTreeEditor/legendCountStore.ts
> +    listeners = listeners.filter((l) => l !== cb);
Please, use a proper variable name for "l"

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/components/SettingsTreeEditor/types.ts
> +  panelTitle?: string;
I'd say this new parameter is unnecessary, check @aneuwald-ctw 's comments

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/index.tsx
> +type Props = {
Please, rename to PieChartPanelAdapterProps.

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +type Props = {
Rename to PieChartProps

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +const defaultConfig: Config = {
Create `.../PieChart/constant.ts` file and move all constants there. Please, keep them in upper case.

```suggestion
const DEFAULT_CONFIG: Config = {
```

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +function handleFrame(state: State, action: Extract<Action, { type: "frame" }>): State {
- Move this function into `.../PieChart/utils/handleFrame.ts`
- Create a proper type for this function. 
```typescript
type HandleFrameProps = {
    state: State,
    action: Extract<Action, { type: "frame" }>
}
```

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +function handlePath(state: State, action: Extract<Action, { type: "path" }>): State {
- Move this function into .../PieChart/utils/handlePath.ts
- Create a proper type for this funcion HandlePathProps

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +function handleSeek(state: State): State {
- Move this function into .../PieChart/utils/handleSeek.ts

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +function reducer(state: State, action: Action): State {
- Move this function into .../PieChart/utils/stateReducer.ts
- Rename to stateReducer

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/settings.ts
> +const supportedDataTypes = [
and use upper case: SUPPORTED_DATA_TYPES

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/settings.ts
> +export function settingsActionReducer(prevConfig: Config, action: SettingsTreeAction): Config {
- Move this function into `.../PieChart/utils/settingsActionReducer.ts`

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/settings.ts
> +export function useSettingsTree(
As you'll move the `settingsActionReducer` function to another file and `useSettingsTree` is a custom hook, it makes sense to rename this file from `settings.ts` to `useSettingsTree.ts`.

2025-05-16 16:57 UTC, luluiz commented on packages/suite-base/src/panels/PieChart/settings.ts
> +  config: Config,
I'd consider creating a type like `UseSettingsTreeProps`

2025-05-16 16:57 UTC, luluiz commented on package.json
> +    "recharts": "2.15.1",
Please, move this `recharts` lib to the proper `package.json`file.
- The correct file: `packages/suite-base/package.json`

2025-05-16 17:04 UTC, luluiz commented on package.json
> +    "recharts": "2.15.1",
And update to the latest version: 2.15.3

2025-05-18 14:38 UTC, yukkysaito commented
@luluiz @aneuwald-ctw cc @Tucker925H 
Thank you for the review. Please give me a moment to check.

2025-05-21 02:17 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +  // log.info("New data received: state", state);
Thanks! That code has already been removed in a later this commit.
The unnecessary logger was removed in [3ac0731](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/3ac0731d9c05a255a0e189954039e2ccc4ad3dc7)

2025-05-21 02:23 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +  const chartData = rawValue.length > 0 ? Array.from(rawValue).map((value) => (value / Array.from(rawValue).reduce((sum, val) => sum + val, 0)) * 100) : [];
Thanks! That code has already been removed in a later this commit.
I created a custom hook named useChartData in [3ac0731](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/3ac0731d9c05a255a0e189954039e2ccc4ad3dc7).

2025-05-22 01:21 UTC, Tucker925H commented on package.json
> +    "recharts": "2.15.1",
fixed at [cdd8793](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/cdd8793b7922e55cb1e6f021298fe8bd0aa44803)

2025-05-29 01:39 UTC, Tucker925H commented on packages/suite-base/src/components/SettingsTreeEditor/NodeEditor.tsx
> +      <>
fixed ad [aec394b](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/aec394b4cba8fb8510d90db90f57f7919fc97256).

2025-05-29 01:42 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +type Props = {
fixed at [ed5b236](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/ed5b2365f9d5002f814abc4ef38c98556a6cb38e).

2025-05-29 01:43 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/index.tsx
> +type Props = {
fixed at [ed5b236](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/ed5b2365f9d5002f814abc4ef38c98556a6cb38e).

2025-05-29 01:44 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/types.ts
> +export type State = {
fixed at [ed5b236](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/ed5b2365f9d5002f814abc4ef38c98556a6cb38e).

2025-05-29 01:45 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/settings.ts
> +const supportedDataTypes = [
fixed at [ed5b236](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/ed5b2365f9d5002f814abc4ef38c98556a6cb38e).

2025-05-29 02:06 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +function handleSeek(state: State): State {
fixed at [122def2](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/122def2bb7af3b57e760c4182fe13caf45317b0e).
remove handlePath function from PieChart.tsx at [d9bdc57](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/d9bdc576a2d2b9251c460cdcec35b119d91c4c51)

2025-05-29 02:09 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +function reducer(state: State, action: Action): State {
fixed at [41aa9a8](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/41aa9a8cefd8db338957cee521d76c75b86f409f)

Rename to stateReducer at [d9bdc57](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/d9bdc576a2d2b9251c460cdcec35b119d91c4c51)

2025-05-29 02:12 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/settings.ts
> +export function useSettingsTree(
fixed at [cca735d](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/cca735dda518cebced96e64cd2ebf6d0908bb8e6).

2025-05-29 02:13 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/settings.ts
> +  config: Config,
fixed at [cca735d](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/cca735dda518cebced96e64cd2ebf6d0908bb8e6).

2025-05-29 02:16 UTC, Tucker925H commented on packages/suite-base/src/components/SettingsTreeEditor/types.ts
> +  panelTitle?: string;
fixed at [dc81f5d](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/dc81f5d9f41ea415d1fc4dee22379d31bebfbd24).

2025-05-29 02:41 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +                  key={`cell-${index}`}
fixed at [d204235](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/d204235b2d984c3bc40121c8df12c9ea0ef27d85).

2025-05-29 02:42 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +              {data.map((entry, index) => (
fixed at [d204235](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/d204235b2d984c3bc40121c8df12c9ea0ef27d85).

2025-05-29 02:55 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +              formatter={(value, name) => {
fixed at [3a220a5](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/3a220a51053616d19b8f0cc04670e1522120d9e9).

2025-06-01 03:13 UTC, Tucker925H commented on packages/suite-base/src/components/SettingsTreeEditor/NodeEditor.tsx
> +      {props.panelTitle === "Pie Chart" && (
fixed at [1f606b3](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/1f606b3013a0e3f4acd927884054044bc1a3605b).

2025-06-04 00:05 UTC, Tucker925H commented
@luluiz  @aneuwald-ctw  cc @yukkysaito 
I've addressed the feedback provided above and would appreciate another round of review.

Currently, I have two remaining TODO items:

1. I'm planning to resolve the conflict with main using git merge origin/main, so that previous comments won't be lost.
2. I'm working on writing test code based on the style of existing sample components.

Thank you!

2025-06-12 03:53 UTC, Tucker925H commented
Hi @luluiz @aneuwald-ctw cc @yukkysaito ,

I’ve completed the initial implementation and have been referring to other OSS code to guide my testing. While I’ve set up some tests, I’d like to confirm a few things before proceeding further.

Could you kindly clarify what exactly should be covered in the tests for this feature? Also, are there any specific cases or patterns you’d recommend following to align with the project's expectations?

I want to make sure the implementation meets the standards and that I’m not missing anything important.

Thank you in advance for your guidance!

2025-06-17 16:48 UTC, luluiz commented
> Hi @luluiz @aneuwald-ctw cc @yukkysaito ,
> 
> I’ve completed the initial implementation and have been referring to other OSS code to guide my testing. While I’ve set up some tests, I’d like to confirm a few things before proceeding further.
> 
> Could you kindly clarify what exactly should be covered in the tests for this feature? Also, are there any specific cases or patterns you’d recommend following to align with the project's expectations?
> 
> I want to make sure the implementation meets the standards and that I’m not missing anything important.
> 
> Thank you in advance for your guidance!

First of all, thank you for your efforts.

We usually aim to cover 80% of the changed code. Hooks, components and util functions are expected to be tested. We usually follow the GWT (given-when-then) pattern for testing.

But I would say not to get too hung up on the 80% number. I would focus more on analysing and trying to cover the points of the code assertively.

There are builders to be used in testing, and we highly recommend using them, since they can make it easier to mock repetitive sections.

There is BasicBuilder with functions to generate mocks of basic data, and builders by domain.
packages/suite-base/src/testing/builders/BasicBuilder.ts

2025-06-26 03:30 UTC, Tucker925H commented
@luluiz cc @aneuwald-ctw, @yukkysaito 
Thank you for the guidance!

I’ve written the test code following the GWT (Given-When-Then) pattern and aimed to cover the key logic of the hooks, components, and utility functions involved. I also made sure to use the available builders, including BasicBuilder, to streamline the setup and avoid redundancy in the tests.

Let me know if there's anything you’d like me to improve or expand on!

2025-07-02 00:22 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +                  key={`cell-${index}`}
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-02 00:22 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +              formatter={(value, name) => {
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-02 00:22 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +              {data.map((entry, index) => (
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-02 00:22 UTC, yukkysaito commented on packages/suite-base/src/components/SettingsTreeEditor/NodeEditor.tsx
> +      <>
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-02 00:22 UTC, yukkysaito commented on packages/suite-base/src/components/SettingsTreeEditor/NodeEditor.tsx
> +      {props.panelTitle === "Pie Chart" && (
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-02 00:23 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/types.ts
> +export type State = {
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-02 00:23 UTC, yukkysaito commented on packages/suite-base/src/components/SettingsTreeEditor/index.tsx
> +          <NodeEditor {...nodeProps} panelTitle={panelInfo?.title} key={nodeProps.key} />
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-02 03:16 UTC, yukkysaito commented
@luluiz @aneuwald-ctw 
I realize you’re busy, but could you please let me know your thoughts on this when you have a moment?

2025-07-02 14:19 UTC, aneuwald-ctw commented on packages/suite-base/src/components/SettingsTreeEditor/LegendControls.tsx
move this to inside the input folder please, as the other inputs. Move also its hook.

2025-07-02 14:21 UTC, aneuwald-ctw commented on packages/suite-base/src/panels/PieChart/PieChart.test.tsx
> +    // Verify that the "No data available" message is displayed when there is no data
you can remove this comments. The name of the tests are clear enough

2025-07-02 14:21 UTC, aneuwald-ctw commented on packages/suite-base/src/panels/PieChart/PieChart.test.tsx
> +    // Verify that the settings editor is updated correctly
same here.

2025-07-02 14:23 UTC, aneuwald-ctw commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +    <div style={{ fontFamily: "Arial, sans-serif", color: "#333" }}>
create a file called PieChart.style.ts and put this styles there. Search other files ended in style.ts and you will see how we do. It is better to not having to dig inside the component .jsx to change styles

2025-07-02 14:24 UTC, aneuwald-ctw commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +  const [config, setConfig] = useState(() => ({
type this state like `useState<PieChartConfig>(() => ...`. That way config would be typed as that and you don't need "config as PieChartConfig" anymore

2025-07-02 14:27 UTC, aneuwald-ctw commented on packages/suite/src/index.ts
> +  | SettingsTreeFieldLegendControll;
typo in Controll with 2 L's

2025-07-02 14:30 UTC, aneuwald-ctw commented
> @luluiz @aneuwald-ctw I realize you’re busy, but could you please let me know your thoughts on this when you have a moment?
> 
> If possible, it would be helpful to receive your response within the next two to three days.

Sorry @yukkysaito  and @Tucker925H, our team was out due to holidays. Please check my suggestions and for me, we are good to go

2025-07-09 03:51 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.test.tsx
> +    // Verify that the "No data available" message is displayed when there is no data
fixed at [281198f](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/281198fa8aa8cc20a803df1f3a4ef36b57b6134e)

2025-07-09 03:51 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.test.tsx
> +    // Verify that the settings editor is updated correctly
fixed at [281198f](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/281198fa8aa8cc20a803df1f3a4ef36b57b6134e)

2025-07-09 03:51 UTC, Tucker925H commented on packages/suite-base/src/components/SettingsTreeEditor/LegendControls.tsx
fixed at [fdeed05](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/fdeed054d9ed6e5b423a9232b9ad8309870b1365)

2025-07-09 03:52 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +  const [config, setConfig] = useState(() => ({
fixed at [47ae78c](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/47ae78cacef01c708fd0dcde7f6bbec96393a3e8).

2025-07-09 03:53 UTC, Tucker925H commented on packages/suite/src/index.ts
> +  | SettingsTreeFieldLegendControll;
fixed at [8a44f7f](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/8a44f7f081522f071e5bdbe01d453a6ba11400b4).

2025-07-09 03:54 UTC, Tucker925H commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +    <div style={{ fontFamily: "Arial, sans-serif", color: "#333" }}>
fixed at [50e43de](https://github.com/lichtblick-suite/lichtblick/pull/315/commits/50e43de097eef988d3986c815778068f6a28a50f).

2025-07-09 04:00 UTC, Tucker925H commented
Hi @aneuwald-ctw (cc: @yukkysaito ),

I've completed all the requested style-related changes and resolved the associated comments.

However, I'm still encountering a SonarQube error during the CI run. I believe it might be related to the test code I added, but I'm not certain.
It seems like the scanner is trying to access an invalid or missing sonar.host.url. Could this be a misconfiguration in the test environment, or something related to how the tests are being picked up by the scanner?

I'd appreciate any advice or suggestions on how to resolve this.

Thanks!

2025-07-14 00:10 UTC, yukkysaito commented on packages/suite/src/index.ts
> +  | SettingsTreeFieldLegendControll;
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-14 00:10 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +  const [config, setConfig] = useState(() => ({
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-14 00:10 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/PieChart.tsx
> +    <div style={{ fontFamily: "Arial, sans-serif", color: "#333" }}>
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-14 00:10 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/PieChart.test.tsx
> +    // Verify that the settings editor is updated correctly
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-14 00:10 UTC, yukkysaito commented on packages/suite-base/src/panels/PieChart/PieChart.test.tsx
> +    // Verify that the "No data available" message is displayed when there is no data
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-14 00:10 UTC, yukkysaito commented on packages/suite-base/src/components/SettingsTreeEditor/LegendControls.tsx
Closing due to lack of response. If there is a problem, please feel free to reopen.

2025-07-15 10:29 UTC, aneuwald-ctw commented
Hey @Tucker925H @yukkysaito thanks so much for the modifications, for me it is ready to merge. But one question, I tried here with an array of numbers (check the Raw Message) and It didn't work.

<img width="1891" height="1051" alt="image" src="https://github.com/user-attachments/assets/ed4d8f0f-e31b-4f5d-b6e2-876b2b9e5aac" />

Should it be an specific schema or format?

Also, the title and the text on the dark mode didn't came very nice, you can use some theme color to be more flexible.

2025-07-16 07:42 UTC, yukkysaito commented
@aneuwald-ctw 
Thank you for confirming. We would like to reproduce the situation on our side as well — could you please share a sample rosbag data with us?

2025-07-16 13:47 UTC, aneuwald-ctw commented
> @aneuwald-ctw Thank you for confirming. We would like to reproduce the situation on our side as well. Could you please share a sample rosbag data with us?

It is the sample data. You can open it in the `Menu` > `Help` > `Explore sample data`.

I can't attach it here because it has more than 25Mb 😞

2025-07-18 13:01 UTC, yukkysaito commented
@aneuwald-ctw Thank you.

I fixed at https://github.com/lichtblick-suite/lichtblick/pull/315/commits/103c5da408563a0a9d070d33f8e519155e15ce87
<img width="1896" height="1290" alt="Screenshot from 2025-07-18 21-50-13" src="https://github.com/user-attachments/assets/d6678c69-d20d-4ab8-8fce-f31cf4be2d36" />

2025-07-21 11:29 UTC, aneuwald-ctw commented
@yukkysaito  Yes it seems great for me now! Now just fix the test and lint and let's merge it!

2025-07-23 06:19 UTC, yukkysaito commented
> @yukkysaito Yes it seems great for me now! Now just fix the test and lint and let's merge it!


@aneuwald-ctw Thank you.
I fixed at https://github.com/lichtblick-suite/lichtblick/pull/315/commits/f14efd1306adecaf6a589798f9d81f07713d1417

2025-07-24 11:39 UTC, aneuwald-ctw approved these changes
lgtm, thanks for the effort guys!

2025-07-24 11:49 UTC, luluiz approved these changes

2025-07-24 11:49 UTC, merged