Plot module Unit tests
Lichtblick-Suite/lichtblick pull request #318
Opened 2024-12-31 11:40 UTC by laisspportugal

**Description**
In order to improve the code coverage, this PR aims to add unit tests for the classes that are not tested yet:

**Tests added:**
- [datum.test.ts](https://github.com/Lichtblick-Suite/lichtblick/compare/feature/plot-unit-tests?expand=1#diff-5ab10b2d7c5c7bd71b3f141b00be5323b24eb2803a897df6086bcf70062f0b50)
- [packages/suite-base/src/panels/Plot/mathFunctions.test.ts](https://github.com/Lichtblick-Suite/lichtblick/compare/feature/plot-unit-tests?expand=1#diff-5436696450e7992ce0b8cd2d53928a5f8d7c77506083184b5f35b356f0db4eee)

**Additional modifications:**

-[removing unreacheable return undefined]( https://github.com/Lichtblick-Suite/lichtblick/compare/feature/plot-unit-tests?expand=1#diff-c42c5542a4998dffa9179f7024706aeb59728ebd3f6448c145455d9d50dd78fcL277)
- Adding more utilitaries to the Basic Builder file
- Moving constants to constant file

**Checklist**

- [ ] The web version was tested and it is running ok
- [ ] The desktop version was tested and it is running ok
- [ ] This change is covered by unit tests
- [ ] Files constants.ts, types.ts and *.style.ts have been checked and relevant code snippets have been relocated

2025-01-06 10:15 UTC, ctw-joao-luis commented on packages/suite-base/src/panels/Plot/PlotLegend.test.tsx
> +import { fireEvent } from "@storybook/testing-library";
I've stumbled upon an article from the creator of the testing-library where he talks about avoiding the use of fireEvent and to use userEvent instead. According to him "[@testing-library/user-event](https://github.com/testing-library/user-event) is a package that's built on top of fireEvent, but it provides several methods that resemble the user interactions more closely."

Link to the blog post: 
https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-testing-libraryuser-event

2025-01-13 14:30 UTC, luluiz commented on packages/suite-base/src/panels/Plot/hooks/usePanning.test.ts
> +/* eslint-disable @typescript-eslint/unbound-method */
@laisspportugal I'd say to open this exception in the lint for test files.
file: .eslintrc.yaml
Add "@typescript-eslint/unbound-method": off in ln 177

2025-01-13 14:35 UTC, luluiz commented on packages/suite-base/src/panels/Plot/hooks/usePanning.test.ts
> +/* eslint-disable @typescript-eslint/unbound-method */
Or solve with:
const spy = jest.spyOn(coordinator, "functionName");
expect(spy)....

2025-01-13 20:44 UTC, laisspportugal commented on packages/suite-base/src/panels/Plot/hooks/usePanning.test.ts
> +/* eslint-disable @typescript-eslint/unbound-method */
Thank you for the feedback. It was fixed by using spy

2025-01-14 15:26 UTC, luluiz requested changes

2025-01-14 15:26 UTC, luluiz commented on packages/suite-base/src/panels/Plot/ChartUtilities/ChartOptions.ts
> +export const getChartOptions = ({
@ctw-joao-luis 
A ChartUtilities folder is unnecessary and out of pattern.
1. rename ChartOptions to getChartOptions.ts and extract to component root folder (/panels/Plot/)
2. EventHandler functions are already implemented by ChartJSManager.ts. So, I'd say to extract addEventListener and removeEventListener to a new file eventHandler.ts and export these functions to be reused in by ChartRenderer.ts

2025-01-14 15:26 UTC, luluiz commented on packages/suite-base/src/panels/Plot/PlotLegend.test.tsx
> +import { fireEvent } from "@storybook/testing-library";
Yes, you're correct.

2025-01-14 18:23 UTC, ctw-joao-luis commented on packages/suite-base/src/panels/Plot/ChartUtilities/ChartOptions.ts
> +export const getChartOptions = ({
Solved on the last commit!

2025-01-15 12:15 UTC, laisspportugal commented on packages/suite-base/src/panels/Plot/PlotLegend.test.tsx
> +import { fireEvent } from "@storybook/testing-library";
Changed to user-event and added the library. Thank you for the hint ;)

2025-01-16 14:58 UTC, laisspportugal commented on packages/suite-base/src/panels/Plot/hooks/useRenderer.test.ts
> +    const theme = createTheme();
Those constants can be moved to the describe session to be reused in the different tests.

2025-01-16 15:00 UTC, laisspportugal commented on packages/suite-base/src/panels/Plot/hooks/useRenderer.test.ts
> +});
```suggestion
Object.defineProperty(HTMLCanvasElement.prototype, "transferControlToOffscreen", {
  value: jest.fn().mockImplementation(() => ({
    width: BasicBuilder.number(),
    height: BasicBuilder.number(),
  })),
});
```

2025-01-17 16:13 UTC, luluiz commented on packages/suite-base/src/panels/Plot/hooks/useRenderer.test.ts
> +    //unmounting the hook
unnecessary comment

2025-01-17 16:36 UTC, luluiz commented on packages/suite-base/src/panels/Plot/hooks/useSubscriptions.test.ts
> +  const setup = (config: PlotConfig = defaultConfig, subscriberId: string = testSubscriber) => {
That's ok. The setup function idea is works like a builder, and works dinamically to override mock whenever necessary.
But it also aims to help with reusability, so returning mocked data for each test to reuse.

I'd say to return like:
```
{
  ...renderHook(...),
  config,
  subescriberId,
  // whatever mocked data used to build de scenario and reusable in the tests
}
```

2025-01-17 16:59 UTC, luluiz commented on packages/suite-base/src/panels/Plot/hooks/useSubscriptions.ts
> +  const { paths: series, xAxisVal: xAxisMode } = config;
Why call `xAxisMode` instead `xAxisVal`?

2025-01-17 21:12 UTC, luluiz commented on packages/suite-base/src/panels/Plot/hooks/useSubscriptions.test.ts
> +    it("sets subscriptions correctly for series paths", () => {
It is missing many situations that can be tested.  I mean, check if the functions were called properly (called, not called, times and with proper value).
functions: 
- isReferenceLinePlotPathType;
- parseMessagePath;
- fillInGlobalVariablesInPath;
- pathToSubscribePayload

2025-01-20 15:09 UTC, luluiz commented on package.json
> +    "@testing-library/user-event": "14.5.2",
This is already imported in "packages/suite-base/package.json"
I suspect this import here is unnecessary.

2025-01-20 15:16 UTC, luluiz approved these changes
I just left a message to check the import related to "user-event". But in general it sounds good and I'm approving this PR.

2025-01-20 15:28 UTC, laisspportugal commented on package.json
> +    "@testing-library/user-event": "14.5.2",
true, removed it

2025-01-20 15:29 UTC, luluiz submitted a review, later dismissed

2025-01-20 15:45 UTC, luluiz approved these changes

2025-01-20 15:46 UTC, merged

2025-01-20 15:48 UTC, ctw-joao-luis commented
Goodbye Plot tests PR, you'll be deeply missed